export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore",
        "revert",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "schedule",
        "checkin",
        "finance",
        "booking",
        "admin",
        "auth",
        "ui",
        "db",
        "test",
        "ci",
        "docs",
        "deps",
      ],
    ],
  },
};
