#!/usr/bin/env python3
"""
Consolidate all migration files from migrations/consolidated/ into a single
bootstrap SQL script suitable for fresh system initialization.

Produces: migrations/000-bootstrap-consolidated.sql
"""

import os
import re
from pathlib import Path

CONSOLIDATED_DIR = Path(__file__).resolve().parent.parent / "migrations" / "consolidated"
OUTPUT_FILE = CONSOLIDATED_DIR / "000-bootstrap-consolidated.sql"


def read_migrations() -> list[tuple[str, str]]:
    """Return sorted (filename, content) tuples for all .sql files."""
    files = sorted(f for f in os.listdir(CONSOLIDATED_DIR) if f.endswith(".sql") and f != "000-bootstrap-consolidated.sql")
    result = []
    for fname in files:
        fpath = CONSOLIDATED_DIR / fname
        content = fpath.read_text(encoding="utf-8")
        result.append((fname, content))
    return result


def apply_fixes(files: list[tuple[str, str]]) -> list[str]:
    """Apply idempotency fixes to each migration file's content."""
    out: list[str] = []

    for fname, content in files:
        # ── 001: strip the _migrations table creation (we create it at the top) ──
        if fname == "001-core-schema.sql":
            content = re.sub(
                r"-- =+\s*\n--\s*0\. Migration tracking table.*?\n-- =+\s*\n\s*CREATE TABLE IF NOT EXISTS _migrations[^;]*;\s*\n",
                "",
                content,
                flags=re.DOTALL,
            )

        # ── 028: guard DROP CONSTRAINT ──
        if fname == "028-fix-loadsheet-sector-fk.sql":
            content = content.replace(
                "ALTER TABLE loadsheet_sectors DROP CONSTRAINT loadsheet_sectors_flight_leg_id_fkey;",
                "DO $$ BEGIN\n  ALTER TABLE loadsheet_sectors DROP CONSTRAINT loadsheet_sectors_flight_leg_id_fkey;\nEXCEPTION WHEN undefined_object THEN NULL;\nEND $$;",
            )

        # ── 032: move CREATE TABLE before ALTER TABLE ──
        if fname == "032-system-settings-seed.sql":
            lines = content.split("\n")
            alter_lines = []
            create_lines = []
            seed_lines = []
            in_section = None
            for line in lines:
                if "ALTER TABLE system_settings" in line:
                    in_section = "alter"
                elif line.strip().startswith("CREATE TABLE IF NOT EXISTS system_settings"):
                    in_section = "create"
                elif line.strip().startswith("INSERT INTO system_settings"):
                    in_section = "seed"

                if in_section == "alter":
                    alter_lines.append(line)
                elif in_section == "create":
                    create_lines.append(line)
                elif in_section == "seed":
                    seed_lines.append(line)
                elif in_section is None and line.strip():
                    out.append(line)  # keep comments above the ALTERs

            content = "\n".join(create_lines + alter_lines + seed_lines)

        # ── 038: guard ADD CONSTRAINT ──
        if fname == "038-per-passenger-overhaul.sql":
            content = content.replace(
                "ALTER TABLE bookings\n  ADD CONSTRAINT chk_bookings_payment_mode CHECK (payment_mode IN ('per_booking', 'per_passenger'));",
                "DO $$ BEGIN\n  ALTER TABLE bookings\n    ADD CONSTRAINT chk_bookings_payment_mode CHECK (payment_mode IN ('per_booking', 'per_passenger'));\nEXCEPTION WHEN duplicate_object THEN NULL;\nEND $$;",
            )

        out.append(content)

    return out


def build_consolidated(parts: list[str]) -> str:
    """Wrap all parts in BEGIN/COMMIT with a clean schema header."""
    header = """-- ============================================================================
-- FIGAS Bootstrap — Consolidated Schema for Fresh Initialization
-- Generated by scripts/consolidate-migrations.py
-- Contains all DDL, triggers, functions, and seed data from
-- migrations/consolidated/001–038 merged into a single idempotent script.
-- ============================================================================

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE TABLE IF NOT EXISTS _migrations (
  id          SERIAL PRIMARY KEY,
  filename    VARCHAR(255) NOT NULL UNIQUE,
  applied_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

INSERT INTO _migrations (filename) VALUES ('000-bootstrap-consolidated.sql');

"""

    footer = """

COMMIT;
"""

    separator = "\n\n-- ============================================================================\n-- End of file section\n-- ============================================================================\n\n"

    body = separator.join(parts)

    return "BEGIN;\n\n" + header + body + footer


def main():
    print("Reading migration files...")
    files = read_migrations()
    print(f"  Found {len(files)} files.")

    print("Applying fixes...")
    parts = apply_fixes(files)

    print("Building consolidated script...")
    output = build_consolidated(parts)

    print(f"Writing {OUTPUT_FILE}...")
    OUTPUT_FILE.write_text(output, encoding="utf-8")

    size_kb = len(output) // 1024
    print(f"  Done — {size_kb:,} KB written.")


if __name__ == "__main__":
    main()
